import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/providers/toaster";
import NextAuthSessionProvider from "@/providers/next-auth-session";
import NextThemesProvider from "@/providers/next-theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Toaster />
        <NextAuthSessionProvider>
          <NextThemesProvider>{children}</NextThemesProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
